# Generated by Django 3.2.23 on 2024-10-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed',
        ),
    ]
